//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration_1_Client.WeatherGenerator {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="WeatherGenerator.WeatherServiceSoap")]
    public interface WeatherServiceSoap {
        
        // CODEGEN: Generating message contract since element name GenerateWeatherResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateWeather", ReplyAction="*")]
        Laboration_1_Client.WeatherGenerator.GenerateWeatherResponse GenerateWeather(Laboration_1_Client.WeatherGenerator.GenerateWeatherRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GenerateWeather", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboration_1_Client.WeatherGenerator.GenerateWeatherResponse> GenerateWeatherAsync(Laboration_1_Client.WeatherGenerator.GenerateWeatherRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateWeatherRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateWeather", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.WeatherGenerator.GenerateWeatherRequestBody Body;
        
        public GenerateWeatherRequest() {
        }
        
        public GenerateWeatherRequest(Laboration_1_Client.WeatherGenerator.GenerateWeatherRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GenerateWeatherRequestBody {
        
        public GenerateWeatherRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GenerateWeatherResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GenerateWeatherResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.WeatherGenerator.GenerateWeatherResponseBody Body;
        
        public GenerateWeatherResponse() {
        }
        
        public GenerateWeatherResponse(Laboration_1_Client.WeatherGenerator.GenerateWeatherResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GenerateWeatherResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string GenerateWeatherResult;
        
        public GenerateWeatherResponseBody() {
        }
        
        public GenerateWeatherResponseBody(string GenerateWeatherResult) {
            this.GenerateWeatherResult = GenerateWeatherResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WeatherServiceSoapChannel : Laboration_1_Client.WeatherGenerator.WeatherServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WeatherServiceSoapClient : System.ServiceModel.ClientBase<Laboration_1_Client.WeatherGenerator.WeatherServiceSoap>, Laboration_1_Client.WeatherGenerator.WeatherServiceSoap {
        
        public WeatherServiceSoapClient() {
        }
        
        public WeatherServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WeatherServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WeatherServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboration_1_Client.WeatherGenerator.GenerateWeatherResponse Laboration_1_Client.WeatherGenerator.WeatherServiceSoap.GenerateWeather(Laboration_1_Client.WeatherGenerator.GenerateWeatherRequest request) {
            return base.Channel.GenerateWeather(request);
        }
        
        public string GenerateWeather() {
            Laboration_1_Client.WeatherGenerator.GenerateWeatherRequest inValue = new Laboration_1_Client.WeatherGenerator.GenerateWeatherRequest();
            inValue.Body = new Laboration_1_Client.WeatherGenerator.GenerateWeatherRequestBody();
            Laboration_1_Client.WeatherGenerator.GenerateWeatherResponse retVal = ((Laboration_1_Client.WeatherGenerator.WeatherServiceSoap)(this)).GenerateWeather(inValue);
            return retVal.Body.GenerateWeatherResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboration_1_Client.WeatherGenerator.GenerateWeatherResponse> Laboration_1_Client.WeatherGenerator.WeatherServiceSoap.GenerateWeatherAsync(Laboration_1_Client.WeatherGenerator.GenerateWeatherRequest request) {
            return base.Channel.GenerateWeatherAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboration_1_Client.WeatherGenerator.GenerateWeatherResponse> GenerateWeatherAsync() {
            Laboration_1_Client.WeatherGenerator.GenerateWeatherRequest inValue = new Laboration_1_Client.WeatherGenerator.GenerateWeatherRequest();
            inValue.Body = new Laboration_1_Client.WeatherGenerator.GenerateWeatherRequestBody();
            return ((Laboration_1_Client.WeatherGenerator.WeatherServiceSoap)(this)).GenerateWeatherAsync(inValue);
        }
    }
}
