//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration_1_Client.LundsMayorService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="LundsMayorService.LundsBorgmastareServiceSoap")]
    public interface LundsBorgmastareServiceSoap {
        
        // CODEGEN: Generating message contract since element name year from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnMayorForSpecificYear", ReplyAction="*")]
        Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearResponse ReturnMayorForSpecificYear(Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ReturnMayorForSpecificYear", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearResponse> ReturnMayorForSpecificYearAsync(Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnMayorForSpecificYearRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnMayorForSpecificYear", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequestBody Body;
        
        public ReturnMayorForSpecificYearRequest() {
        }
        
        public ReturnMayorForSpecificYearRequest(Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnMayorForSpecificYearRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string year;
        
        public ReturnMayorForSpecificYearRequestBody() {
        }
        
        public ReturnMayorForSpecificYearRequestBody(string year) {
            this.year = year;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ReturnMayorForSpecificYearResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ReturnMayorForSpecificYearResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearResponseBody Body;
        
        public ReturnMayorForSpecificYearResponse() {
        }
        
        public ReturnMayorForSpecificYearResponse(Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ReturnMayorForSpecificYearResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ReturnMayorForSpecificYearResult;
        
        public ReturnMayorForSpecificYearResponseBody() {
        }
        
        public ReturnMayorForSpecificYearResponseBody(string ReturnMayorForSpecificYearResult) {
            this.ReturnMayorForSpecificYearResult = ReturnMayorForSpecificYearResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LundsBorgmastareServiceSoapChannel : Laboration_1_Client.LundsMayorService.LundsBorgmastareServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LundsBorgmastareServiceSoapClient : System.ServiceModel.ClientBase<Laboration_1_Client.LundsMayorService.LundsBorgmastareServiceSoap>, Laboration_1_Client.LundsMayorService.LundsBorgmastareServiceSoap {
        
        public LundsBorgmastareServiceSoapClient() {
        }
        
        public LundsBorgmastareServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LundsBorgmastareServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LundsBorgmastareServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LundsBorgmastareServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearResponse Laboration_1_Client.LundsMayorService.LundsBorgmastareServiceSoap.ReturnMayorForSpecificYear(Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequest request) {
            return base.Channel.ReturnMayorForSpecificYear(request);
        }
        
        public string ReturnMayorForSpecificYear(string year) {
            Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequest inValue = new Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequest();
            inValue.Body = new Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequestBody();
            inValue.Body.year = year;
            Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearResponse retVal = ((Laboration_1_Client.LundsMayorService.LundsBorgmastareServiceSoap)(this)).ReturnMayorForSpecificYear(inValue);
            return retVal.Body.ReturnMayorForSpecificYearResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearResponse> Laboration_1_Client.LundsMayorService.LundsBorgmastareServiceSoap.ReturnMayorForSpecificYearAsync(Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequest request) {
            return base.Channel.ReturnMayorForSpecificYearAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearResponse> ReturnMayorForSpecificYearAsync(string year) {
            Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequest inValue = new Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequest();
            inValue.Body = new Laboration_1_Client.LundsMayorService.ReturnMayorForSpecificYearRequestBody();
            inValue.Body.year = year;
            return ((Laboration_1_Client.LundsMayorService.LundsBorgmastareServiceSoap)(this)).ReturnMayorForSpecificYearAsync(inValue);
        }
    }
}
