//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecutbildning.Color", ConfigurationName="IColor")]
public interface IColor
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecutbildning.Color/IColor/IsColor", ReplyAction="http://Ecutbildning.Color/IColor/IsColorResponse")]
    string IsColor(string color);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecutbildning.Color/IColor/IsColor", ReplyAction="http://Ecutbildning.Color/IColor/IsColorResponse")]
    System.Threading.Tasks.Task<string> IsColorAsync(string color);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IColorChannel : IColor, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class ColorClient : System.ServiceModel.ClientBase<IColor>, IColor
{
    
    public ColorClient()
    {
    }
    
    public ColorClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ColorClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ColorClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ColorClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string IsColor(string color)
    {
        return base.Channel.IsColor(color);
    }
    
    public System.Threading.Tasks.Task<string> IsColorAsync(string color)
    {
        return base.Channel.IsColorAsync(color);
    }
}
