//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration_1_Client.SubtractTwoNumbersService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SubtractTwoNumbersService.SubtractTwoNumbersServiceSoap")]
    public interface SubtractTwoNumbersServiceSoap {
        
        // CODEGEN: Generating message contract since element name x from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractTwoNumbers", ReplyAction="*")]
        Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersResponse SubtractTwoNumbers(Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SubtractTwoNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersResponse> SubtractTwoNumbersAsync(Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractTwoNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractTwoNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequestBody Body;
        
        public SubtractTwoNumbersRequest() {
        }
        
        public SubtractTwoNumbersRequest(Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractTwoNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string y;
        
        public SubtractTwoNumbersRequestBody() {
        }
        
        public SubtractTwoNumbersRequestBody(string x, string y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SubtractTwoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SubtractTwoNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersResponseBody Body;
        
        public SubtractTwoNumbersResponse() {
        }
        
        public SubtractTwoNumbersResponse(Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SubtractTwoNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SubtractTwoNumbersResult;
        
        public SubtractTwoNumbersResponseBody() {
        }
        
        public SubtractTwoNumbersResponseBody(string SubtractTwoNumbersResult) {
            this.SubtractTwoNumbersResult = SubtractTwoNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SubtractTwoNumbersServiceSoapChannel : Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SubtractTwoNumbersServiceSoapClient : System.ServiceModel.ClientBase<Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersServiceSoap>, Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersServiceSoap {
        
        public SubtractTwoNumbersServiceSoapClient() {
        }
        
        public SubtractTwoNumbersServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SubtractTwoNumbersServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubtractTwoNumbersServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SubtractTwoNumbersServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersResponse Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersServiceSoap.SubtractTwoNumbers(Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequest request) {
            return base.Channel.SubtractTwoNumbers(request);
        }
        
        public string SubtractTwoNumbers(string x, string y) {
            Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequest inValue = new Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequest();
            inValue.Body = new Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersResponse retVal = ((Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersServiceSoap)(this)).SubtractTwoNumbers(inValue);
            return retVal.Body.SubtractTwoNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersResponse> Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersServiceSoap.SubtractTwoNumbersAsync(Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequest request) {
            return base.Channel.SubtractTwoNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersResponse> SubtractTwoNumbersAsync(string x, string y) {
            Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequest inValue = new Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequest();
            inValue.Body = new Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((Laboration_1_Client.SubtractTwoNumbersService.SubtractTwoNumbersServiceSoap)(this)).SubtractTwoNumbersAsync(inValue);
        }
    }
}
