//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://Ecutbildning.DateString", ConfigurationName="IDateAsString")]
public interface IDateAsString
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecutbildning.DateString/IDateAsString/ReturnDateAsString", ReplyAction="http://Ecutbildning.DateString/IDateAsString/ReturnDateAsStringResponse")]
    string ReturnDateAsString(string input);
    
    [System.ServiceModel.OperationContractAttribute(Action="http://Ecutbildning.DateString/IDateAsString/ReturnDateAsString", ReplyAction="http://Ecutbildning.DateString/IDateAsString/ReturnDateAsStringResponse")]
    System.Threading.Tasks.Task<string> ReturnDateAsStringAsync(string input);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public interface IDateAsStringChannel : IDateAsString, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
public partial class DateAsStringClient : System.ServiceModel.ClientBase<IDateAsString>, IDateAsString
{
    
    public DateAsStringClient()
    {
    }
    
    public DateAsStringClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public DateAsStringClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DateAsStringClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public DateAsStringClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public string ReturnDateAsString(string input)
    {
        return base.Channel.ReturnDateAsString(input);
    }
    
    public System.Threading.Tasks.Task<string> ReturnDateAsStringAsync(string input)
    {
        return base.Channel.ReturnDateAsStringAsync(input);
    }
}
