//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration_1_Client.AddTwoNumbersService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddTwoNumbersService.AddTwoNumbersServiceSoap")]
    public interface AddTwoNumbersServiceSoap {
        
        // CODEGEN: Generating message contract since element name x from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersResponse AddTwoNumbers(Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersResponse> AddTwoNumbersAsync(Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequestBody Body;
        
        public AddTwoNumbersRequest() {
        }
        
        public AddTwoNumbersRequest(Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string y;
        
        public AddTwoNumbersRequestBody() {
        }
        
        public AddTwoNumbersRequestBody(string x, string y) {
            this.x = x;
            this.y = y;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddTwoNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddTwoNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersResponseBody Body;
        
        public AddTwoNumbersResponse() {
        }
        
        public AddTwoNumbersResponse(Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddTwoNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddTwoNumbersResult;
        
        public AddTwoNumbersResponseBody() {
        }
        
        public AddTwoNumbersResponseBody(string AddTwoNumbersResult) {
            this.AddTwoNumbersResult = AddTwoNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddTwoNumbersServiceSoapChannel : Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddTwoNumbersServiceSoapClient : System.ServiceModel.ClientBase<Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap>, Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap {
        
        public AddTwoNumbersServiceSoapClient() {
        }
        
        public AddTwoNumbersServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddTwoNumbersServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoNumbersServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoNumbersServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersResponse Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap.AddTwoNumbers(Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbers(request);
        }
        
        public string AddTwoNumbers(string x, string y) {
            Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequest inValue = new Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequest();
            inValue.Body = new Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersResponse retVal = ((Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap)(this)).AddTwoNumbers(inValue);
            return retVal.Body.AddTwoNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersResponse> Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap.AddTwoNumbersAsync(Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequest request) {
            return base.Channel.AddTwoNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersResponse> AddTwoNumbersAsync(string x, string y) {
            Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequest inValue = new Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequest();
            inValue.Body = new Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            return ((Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap)(this)).AddTwoNumbersAsync(inValue);
        }
    }
}
