//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration_1_Client.AddTwoNumbersService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddTwoNumbersService.AddTwoNumbersServiceSoap")]
    public interface AddTwoNumbersServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        float AddTwoNumbers(float x, float y);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddTwoNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<float> AddTwoNumbersAsync(float x, float y);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddTwoNumbersServiceSoapChannel : Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddTwoNumbersServiceSoapClient : System.ServiceModel.ClientBase<Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap>, Laboration_1_Client.AddTwoNumbersService.AddTwoNumbersServiceSoap {
        
        public AddTwoNumbersServiceSoapClient() {
        }
        
        public AddTwoNumbersServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddTwoNumbersServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoNumbersServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddTwoNumbersServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public float AddTwoNumbers(float x, float y) {
            return base.Channel.AddTwoNumbers(x, y);
        }
        
        public System.Threading.Tasks.Task<float> AddTwoNumbersAsync(float x, float y) {
            return base.Channel.AddTwoNumbersAsync(x, y);
        }
    }
}
