//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration_1_Client.AddThreeNumbersService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="AddThreeNumbersService.AddThreeNumbersServiceSoap")]
    public interface AddThreeNumbersServiceSoap {
        
        // CODEGEN: Generating message contract since element name x from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddThreeNumbers", ReplyAction="*")]
        Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersResponse AddThreeNumbers(Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/AddThreeNumbers", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersResponse> AddThreeNumbersAsync(Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddThreeNumbersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddThreeNumbers", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequestBody Body;
        
        public AddThreeNumbersRequest() {
        }
        
        public AddThreeNumbersRequest(Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddThreeNumbersRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string x;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string y;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string z;
        
        public AddThreeNumbersRequestBody() {
        }
        
        public AddThreeNumbersRequestBody(string x, string y, string z) {
            this.x = x;
            this.y = y;
            this.z = z;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddThreeNumbersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddThreeNumbersResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersResponseBody Body;
        
        public AddThreeNumbersResponse() {
        }
        
        public AddThreeNumbersResponse(Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class AddThreeNumbersResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddThreeNumbersResult;
        
        public AddThreeNumbersResponseBody() {
        }
        
        public AddThreeNumbersResponseBody(string AddThreeNumbersResult) {
            this.AddThreeNumbersResult = AddThreeNumbersResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddThreeNumbersServiceSoapChannel : Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddThreeNumbersServiceSoapClient : System.ServiceModel.ClientBase<Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersServiceSoap>, Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersServiceSoap {
        
        public AddThreeNumbersServiceSoapClient() {
        }
        
        public AddThreeNumbersServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddThreeNumbersServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddThreeNumbersServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddThreeNumbersServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersResponse Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersServiceSoap.AddThreeNumbers(Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequest request) {
            return base.Channel.AddThreeNumbers(request);
        }
        
        public string AddThreeNumbers(string x, string y, string z) {
            Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequest inValue = new Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequest();
            inValue.Body = new Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            inValue.Body.z = z;
            Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersResponse retVal = ((Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersServiceSoap)(this)).AddThreeNumbers(inValue);
            return retVal.Body.AddThreeNumbersResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersResponse> Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersServiceSoap.AddThreeNumbersAsync(Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequest request) {
            return base.Channel.AddThreeNumbersAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersResponse> AddThreeNumbersAsync(string x, string y, string z) {
            Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequest inValue = new Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequest();
            inValue.Body = new Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersRequestBody();
            inValue.Body.x = x;
            inValue.Body.y = y;
            inValue.Body.z = z;
            return ((Laboration_1_Client.AddThreeNumbersService.AddThreeNumbersServiceSoap)(this)).AddThreeNumbersAsync(inValue);
        }
    }
}
