//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Laboration_1_Client.NameDayService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="NameDayService.NameDaySoap")]
    public interface NameDaySoap {
        
        // CODEGEN: Generating message contract since element name name from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateOfNameDay", ReplyAction="*")]
        Laboration_1_Client.NameDayService.DateOfNameDayResponse DateOfNameDay(Laboration_1_Client.NameDayService.DateOfNameDayRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DateOfNameDay", ReplyAction="*")]
        System.Threading.Tasks.Task<Laboration_1_Client.NameDayService.DateOfNameDayResponse> DateOfNameDayAsync(Laboration_1_Client.NameDayService.DateOfNameDayRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DateOfNameDayRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DateOfNameDay", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.NameDayService.DateOfNameDayRequestBody Body;
        
        public DateOfNameDayRequest() {
        }
        
        public DateOfNameDayRequest(Laboration_1_Client.NameDayService.DateOfNameDayRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DateOfNameDayRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string name;
        
        public DateOfNameDayRequestBody() {
        }
        
        public DateOfNameDayRequestBody(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DateOfNameDayResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DateOfNameDayResponse", Namespace="http://tempuri.org/", Order=0)]
        public Laboration_1_Client.NameDayService.DateOfNameDayResponseBody Body;
        
        public DateOfNameDayResponse() {
        }
        
        public DateOfNameDayResponse(Laboration_1_Client.NameDayService.DateOfNameDayResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DateOfNameDayResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DateOfNameDayResult;
        
        public DateOfNameDayResponseBody() {
        }
        
        public DateOfNameDayResponseBody(string DateOfNameDayResult) {
            this.DateOfNameDayResult = DateOfNameDayResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface NameDaySoapChannel : Laboration_1_Client.NameDayService.NameDaySoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class NameDaySoapClient : System.ServiceModel.ClientBase<Laboration_1_Client.NameDayService.NameDaySoap>, Laboration_1_Client.NameDayService.NameDaySoap {
        
        public NameDaySoapClient() {
        }
        
        public NameDaySoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public NameDaySoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameDaySoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public NameDaySoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        Laboration_1_Client.NameDayService.DateOfNameDayResponse Laboration_1_Client.NameDayService.NameDaySoap.DateOfNameDay(Laboration_1_Client.NameDayService.DateOfNameDayRequest request) {
            return base.Channel.DateOfNameDay(request);
        }
        
        public string DateOfNameDay(string name) {
            Laboration_1_Client.NameDayService.DateOfNameDayRequest inValue = new Laboration_1_Client.NameDayService.DateOfNameDayRequest();
            inValue.Body = new Laboration_1_Client.NameDayService.DateOfNameDayRequestBody();
            inValue.Body.name = name;
            Laboration_1_Client.NameDayService.DateOfNameDayResponse retVal = ((Laboration_1_Client.NameDayService.NameDaySoap)(this)).DateOfNameDay(inValue);
            return retVal.Body.DateOfNameDayResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<Laboration_1_Client.NameDayService.DateOfNameDayResponse> Laboration_1_Client.NameDayService.NameDaySoap.DateOfNameDayAsync(Laboration_1_Client.NameDayService.DateOfNameDayRequest request) {
            return base.Channel.DateOfNameDayAsync(request);
        }
        
        public System.Threading.Tasks.Task<Laboration_1_Client.NameDayService.DateOfNameDayResponse> DateOfNameDayAsync(string name) {
            Laboration_1_Client.NameDayService.DateOfNameDayRequest inValue = new Laboration_1_Client.NameDayService.DateOfNameDayRequest();
            inValue.Body = new Laboration_1_Client.NameDayService.DateOfNameDayRequestBody();
            inValue.Body.name = name;
            return ((Laboration_1_Client.NameDayService.NameDaySoap)(this)).DateOfNameDayAsync(inValue);
        }
    }
}
